# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Get Mode
#' @description Get the mode of a vector.
#'
#' This function calculates the mode of a numeric vector.
#'
#' @param v A numeric vector.
#' @return The mode of the input vector as an integer.
#' @export
getmode <- function(v) {
    .Call(`_SLCMRT_getmode`, v)
}

#' @title Generate Random Normal Samples
#' @description Generate random samples from a normal distribution with given mean and standard deviation.
#'
#' This function generates random samples from a normal distribution with given mean (\code{mu}) and standard deviation (\code{sigma}).
#'
#' @param mu A numeric vector specifying the mean of the normal distribution.
#' @param sigma A numeric vector specifying the standard deviation of the normal distribution.
#' @return A numeric vector of random samples.
#' @export
myrnorm <- function(mu, sigma) {
    .Call(`_SLCMRT_myrnorm`, mu, sigma)
}

#' @title Generate Bernoulli Random Sample
#' @description Generate a Bernoulli random sample with given probability of success.
#'
#' This function generates a single Bernoulli random sample with the specified probability (\code{prob}) of success.
#'
#' @param prob A numeric value specifying the probability of success.
#' @return An integer indicating the outcome of the Bernoulli trial (0 or 1).
#' @export
rbernoulli_one <- function(prob) {
    .Call(`_SLCMRT_rbernoulli_one`, prob)
}

#' @title Generate Truncated Normal Sample
#' @description Generate a truncated normal sample with specified mean, standard deviation, truncation direction, and truncation bound.
#'
#' This function generates a single truncated normal sample with the specified mean (\code{mu}), standard deviation (\code{sigma}),
#' truncation direction (\code{y}), and truncation bound (\code{c}).
#'
#' @param mu A numeric value specifying the mean of the normal distribution.
#' @param sigma A numeric value specifying the standard deviation of the normal distribution.
#' @param y A numeric value specifying the truncation direction (0 for upper bound, 1 for lower bound).
#' @param c A numeric value specifying the truncation bound.
#' @return A numeric value representing the truncated normal sample.
#' @export
rTruncNorm_1b <- function(mu, sigma, y, c) {
    .Call(`_SLCMRT_rTruncNorm_1b`, mu, sigma, y, c)
}

#' @title Generate Dirichlet Sample
#' @description Generate a random sample from a Dirichlet distribution with given parameters.
#'
#' This function generates a single random sample from a Dirichlet distribution with parameters specified by the vector \code{deltas}.
#'
#' @param deltas A numeric vector specifying the parameters of the Dirichlet distribution.
#' @return A numeric vector representing the generated Dirichlet sample.
#' @export
rDirichlet <- function(deltas) {
    .Call(`_SLCMRT_rDirichlet`, deltas)
}

#' @title Generate Truncated Normal Sample
#' @description Generate a truncated normal sample with specified mean, standard deviation, multinomial result, and cumulative probabilities
#' given the multinomial distribution.
#'
#' This function generates a single truncated normal sample with the specified mean (\code{mean}), standard deviation (\code{sd}),
#' response category (\code{w}), and cumulative probabilities (\code{ps}).
#'
#' @param mean A numeric value specifying the mean of the normal distribution.
#' @param sd A numeric value specifying the standard deviation of the normal distribution.
#' @param w A numeric value specifying the response category.
#' @param ps A numeric vector of cumulative probabilities.
#' @return A numeric value representing the truncated normal sample.
#' @export
rTruncNorm <- function(mean, sd, w, ps) {
    .Call(`_SLCMRT_rTruncNorm`, mean, sd, w, ps)
}

#' @title Generate Multinomial Sample
#' @description Generate a multinomial sample with given probabilities.
#'
#' This function generates a single multinomial sample with the specified probabilities (\code{ps}).
#'
#' @param ps A numeric vector specifying the probabilities of each category.
#' @return An unsigned integer representing the generated multinomial sample.
#' @export
rmultinomial <- function(ps) {
    .Call(`_SLCMRT_rmultinomial`, ps)
}

#' @title Get Bijection Vector
#' @description Get the bijection vector for a given number of attributes and level of attribute.
#'
#' This function calculates the bijection vector for a specified number of attributes (K) and level of attribute (M).
#'
#' @param K Number of attributes.
#' @param M Level of attribute.
#' @return The bijection vector.
#' @examples
#' gen_bijectionvector(3, 2)
#' @export
gen_bijectionvector <- function(K, M) {
    .Call(`_SLCMRT_gen_bijectionvector`, K, M)
}

#' @title Inverse Generate Bijection Vector
#' @description Inverse function of generating the bijection vector for a given number of attributes and level of attribute.
#'
#' This function calculates the inverse of the function that generates the bijection vector for a specified number of attributes (K),
#' level of attribute (M), and cumulative value (CL).
#'
#' @param K Number of attributes.
#' @param M Level of attribute.
#' @param CL Cumulative value.
#' @return A numeric vector representing the inverse bijection vector.
#' @export
inv_gen_bijectionvector <- function(K, M, CL) {
    .Call(`_SLCMRT_inv_gen_bijectionvector`, K, M, CL)
}

#' @title Generate Inverse Bijection Table
#' @description Generate a table of inverse bijection vectors for given parameters.
#'
#' This function generates a table of inverse bijection vectors for a specified number of attributes (K), level of attribute (M), and number of classes (nClass).
#'
#' @param K Number of attributes.
#' @param M Level of attribute.
#' @param nClass Number of classes.
#' @return A matrix representing the generated inverse bijection table.
#' @export
CL_gen_invbijection_table <- function(K, M, nClass) {
    .Call(`_SLCMRT_CL_gen_invbijection_table`, K, M, nClass)
}

#' @title Generate Attribute Table
#' @description Generate attribute-related tables based on specified parameters.
#'
#' This function generates attribute-related tables including the attribute table (\code{Atable}), lower bound table (\code{LBtable}),
#' index table (\code{finalcols}), D-to-Q table (\code{DtoQtable}), adjacency table (\code{adjtable}), and item index table (\code{itemindexnum})
#' based on the provided parameters including the number of classes (\code{nClass}), the number of attributes (\code{K}),
#' the number of levels of attribute (\code{M}).
#'
#' @param nClass Number of classes.
#' @param K Number of attributes.
#' @param M Levels of attribute.
#' @return A list containing the generated tables.
#' @export
GenerateAtable <- function(nClass, K, M) {
    .Call(`_SLCMRT_GenerateAtable`, nClass, K, M)
}

#' @title Update the latent speed coefficients Tau
#' @description Update the latent speed coefficients Tau using MCMC sampling.
#'
#' This function updates the latent speed coefficients Tau using MCMC sampling.
#'
#' @param N Number of respondents.
#' @param J Number of items.
#' @param Eta A numeric vector of item response time parameters.
#' @param sigma2_t A numeric vector of item response time variances.
#' @param logt A numeric matrix of log-transformed response time.
#' @param alpha A numeric matrix of attribute profiles by respondents.
#' @param H A numeric matrix of item-attribute response time coefficients.
#' @return A numeric vector.
#' @export
Update_Tau <- function(N, J, Eta, sigma2_t, logt, alpha, H) {
    .Call(`_SLCMRT_Update_Tau`, N, J, Eta, sigma2_t, logt, alpha, H)
}

#' @title Update Sigma2_t
#' @description Update Sigma2_t using MCMC sampling.
#'
#' This function updates Sigma2_t using MCMC sampling.
#'
#' @param N Number of respondents.
#' @param J Number of items.
#' @param Eta A numeric vector of item response time parameters.
#' @param Tau A numeric vector of the latent speed Tau values.
#' @param logt A numeric matrix of log-transformed response time.
#' @param alpha A numeric matrix of attribute profiles by respondents.
#' @param H A numeric matrix of item-attribute response time coefficients.
#' @param a_t Shape parameter for the gamma distribution.
#' @param b_t Rate parameter for the gamma distribution.
#' @return A numeric vector of updated Sigma2_t values.
#' @export
Update_sigma2_t <- function(N, J, Eta, Tau, logt, alpha, H, a_t, b_t) {
    .Call(`_SLCMRT_Update_sigma2_t`, N, J, Eta, Tau, logt, alpha, H, a_t, b_t)
}

#' @title Update Eta
#' @description Update Eta using MCMC sampling.
#'
#' This function updates Eta using MCMC sampling.
#'
#' @param N Number of respondents.
#' @param J Number of items.
#' @param Tau A numeric vector of latent speed coefficients.
#' @param logt A numeric matrix of log-transformed response time.
#' @param alpha A numeric matrix of attribute profiles by respondents.
#' @param H A numeric matrix of item-attribute response time coefficients.
#' @param sigma2_t A numeric vector of item response time variances.
#' @param sigma2_eta Variance parameter for the Eta sampling.
#' @return A numeric vector of updated Eta values.
#' @export
Update_Eta <- function(N, J, Tau, logt, alpha, H, sigma2_t, sigma2_eta) {
    .Call(`_SLCMRT_Update_Eta`, N, J, Tau, logt, alpha, H, sigma2_t, sigma2_eta)
}

#' @title Update Delta
#' @description Sample delta.
#'
#' This function samples from the DJP (Double Joint Probability) distribution.
#'
#' @param Bplb Lower bound for Bp.
#' @param omega Omega parameter.
#' @param sigma_B Standard deviation for B.
#' @param Bp Bp parameter.
#' @param ApApp ApApp parameter.
#' @param ApAb ApAb parameter.
#' @param ApZjp ApZjp parameter.
#' @param term_h Additional term related to H.
#' @return A double value.
#' @export
djpsamp <- function(Bplb, omega, sigma_B, Bp, ApApp, ApAb, ApZjp, term_h) {
    .Call(`_SLCMRT_djpsamp`, Bplb, omega, sigma_B, Bp, ApApp, ApAb, ApZjp, term_h)
}

#' @title Compute Lower Bound
#' @description Compute the lower bound for a given parameter.
#'
#' This function computes the lower bound for a given parameter based on provided tables and coefficients.
#'
#' @param nClass Number of classes.
#' @param LBtable Matrix representing the lower bound constraints.
#' @param Atable Matrix representing the attribute profile table.
#' @param p Index of the parameter.
#' @param betaj Row vector of item response coefficient matrix B.
#' @param Bp Bp parameter.
#' @param Bindices Vector of latent class indices.
#' @return The computed lower bound.
#' @export
computeLB <- function(nClass, LBtable, Atable, p, betaj, Bp, Bindices) {
    .Call(`_SLCMRT_computeLB`, nClass, LBtable, Atable, p, betaj, Bp, Bindices)
}

#' @title Update Alpha
#' @description Update alpha values using MCMC sampling.
#'
#' This function updates alpha values based on provided parameters using MCMC sampling.
#'
#' @param N Number of respondents.
#' @param J Number of items.
#' @param nClass Number of classes.
#' @param Y Matrix of categorical responses.
#' @param CLASS Vector of class labels.
#' @param PY_a Cube of conditional probabilities.
#' @param pis Vector of latent class proportion parameters.
#' @param Atable Matrix representing the attribute profile table.
#' @param alpha Matrix of attribute profiles by respondents.
#' @param d0 Dirichlet distribution parameter.
#' @param logt Matrix of log-transformed response times.
#' @param Eta Vector of item response time parameters.
#' @param Tau Vector of latent speed coefficients.
#' @param H Matrix of item-attribute response time coefficients.
#' @param sigma2_t Vector of item response time variances.
#' @return A list containing updated values.
#' @export
Update_alpha_SLCMRT <- function(N, J, nClass, Y, CLASS, PY_a, pis, Atable, alpha, d0, logt, Eta, Tau, H, sigma2_t) {
    .Call(`_SLCMRT_Update_alpha_SLCMRT`, N, J, nClass, Y, CLASS, PY_a, pis, Atable, alpha, d0, logt, Eta, Tau, H, sigma2_t)
}

#' @title Simulate Y star.
#' @description Simulate a matrix of categorical responses.
#'
#' This function simulates a matrix of categorical responses using the provided parameters and an adjusted sampling technique.
#'
#' @param N Number of respondents.
#' @param J Number of items.
#' @param Y Matrix of categorical responses.
#' @param CLASS Vector of class labels.
#' @param PY_a Cube of conditional probabilities.
#' @param ABETA Matrix of adjusted item response coefficients.
#' @return A matrix of simulated categorical responses.
#' @export
simYast <- function(N, J, Y, CLASS, PY_a, ABETA) {
    .Call(`_SLCMRT_simYast`, N, J, Y, CLASS, PY_a, ABETA)
}

#' @title Compute Conditional Probabilities
#' @description Compute conditional probabilities based on provided parameters.
#'
#' This function computes conditional probabilities based on the provided attribute profile table, item response coefficient matrix, and item response threshold matrix.
#'
#' @param J Number of items.
#' @param P Number of levels for each item.
#' @param nClass Number of classes.
#' @param Atable Matrix representing the attribute profile table.
#' @param BETA Matrix representing the item response coefficient matrix.
#' @param Kappa Matrix representing the item response threshold matrix.
#' @return A list containing the adjusted item response coefficient matrix (ABETA) and the cube of conditional probabilities (PY_a).
#' @export
computePYa <- function(J, P, nClass, Atable, BETA, Kappa) {
    .Call(`_SLCMRT_computePYa`, J, P, nClass, Atable, BETA, Kappa)
}

#' @title Check Strict Identifiability Condition
#' @description Check if the Delta matrix satisfies the strict identifiability condition.
#'
#' This function checks if the provided Delta matrix satisfies the strict identifiability condition based on the given parameters.
#'
#' @param DELTA Matrix representing the Delta matrix.
#' @param completematrix Matrix used to check block diagonal matrix.
#' @param M Levels of attribute.
#' @param K Number of attribute.
#' @param ncomp Number of parameters.
#' @param mainorder A vector representing the main order of the parameters.
#' @return A boolean indicating whether the strict identifiability condition is satisfied.
#' @export
identify_strictcheck <- function(DELTA, completematrix, M, K, ncomp, mainorder) {
    .Call(`_SLCMRT_identify_strictcheck`, DELTA, completematrix, M, K, ncomp, mainorder)
}

#' @title Update H, D and B matrix
#' @description Update the HDB matrix with strict identifiability condition.
#'
#' This function updates the HDB matrix with strict identifiability condition using the provided parameters.
#' The H coefficients are negative in default.
#'
#' @param J Number of items.
#' @param N Number of respondents.
#' @param M Levels of attribute.
#' @param K Number of attributes.
#' @param nClass Number of classes.
#' @param sigma2_h Variance parameter for H.
#' @param alpha Matrix of attribute profiles by respondents.
#' @param sigma2_t Vector of variance parameters for the response time.
#' @param logt Matrix of log-transformed response time.
#' @param Atable Matrix representing the attribute profile table.
#' @param H Matrix of item-attribute response time coefficients.
#' @param Eta Vector of item response time coefficients.
#' @param Tau Vector of latent speed coefficients.
#' @param DELTA Matrix representing the item-attribute structure.
#' @param omega Hyperparameter.
#' @param Yast Matrix representing simulated responses.
#' @param BETA Matrix representing the item response coefficient matrix.
#' @param ABETA Matrix representing the item response coefficient matrix.
#' @param sigma_B Variance parameter for B.
#' @param main Vector representing the column index of the main-effect parameters.
#' @param mainorder Vector representing the index of the beta coefficients.
#' @param completematrix Matrix used to check the identifiablity constraints.
#' @param LBtable Matrix representing the lower bound table.
#' @param Bindices Vector representing the latent class indices.
#' @return None. The function updates the HDB matrix in place.
#' @export
Update_HDB_strict <- function(J, N, M, K, nClass, sigma2_h, alpha, sigma2_t, logt, Atable, H, Eta, Tau, DELTA, omega, Yast, BETA, ABETA, sigma_B, main, mainorder, completematrix, LBtable, Bindices) {
    invisible(.Call(`_SLCMRT_Update_HDB_strict`, J, N, M, K, nClass, sigma2_h, alpha, sigma2_t, logt, Atable, H, Eta, Tau, DELTA, omega, Yast, BETA, ABETA, sigma_B, main, mainorder, completematrix, LBtable, Bindices))
}

#' Update_alpha
#'
#' Update the alpha parameters in the SLCM model.
#'
#' @param N An integer specifying the number of observations.
#' @param J An integer specifying the number of items.
#' @param nClass An integer specifying the number of latent classes.
#' @param Y Matrix of categorical responses.
#' @param CLASS Vector of class labels.
#' @param PY_a A cube containing the conditional probabilities for each observation-feature combination and class.
#' @param pis Vector of latent class proportion parameters.
#' @param Atable Matrix representing the attribute profile table.
#' @param alpha Matrix of attribute profiles by respondents.
#' @param d0 A vector of hyper parameters.
#'
#' @return A list containing the updated parameters:
#' \itemize{
#'   \item pis: Updated class proportions.
#'   \item CLASS: Updated class assignments.
#'   \item alpha: Updated alpha parameters.
#' }
#'
#' @export
Update_alpha <- function(N, J, nClass, Y, CLASS, PY_a, pis, Atable, alpha, d0) {
    .Call(`_SLCMRT_Update_alpha`, N, J, nClass, Y, CLASS, PY_a, pis, Atable, alpha, d0)
}

#' Update_DB
#'
#' Update BETA and DELTA parameters.
#'
#' @param J An integer specifying the number of rows.
#' @param M An integer specifying the number of components.
#' @param K An integer specifying the number of factors.
#' @param alpha A matrix containing alpha values.
#' @param nClass An integer specifying the number of classes.
#' @param Yast A matrix containing Yast values.
#' @param BETA A matrix containing BETA values.
#' @param DELTA A matrix containing DELTA values.
#' @param ABETA A matrix containing ABETA values.
#' @param Atable A matrix containing Atable values.
#' @param sigma_B A double specifying the parameter sigma_B.
#' @param omega A double specifying the parameter omega.
#'
#' @return A list containing updated BETA, DELTA, and ABETA values.
#'
#' @export
Update_DB <- function(J, M, K, alpha, nClass, Yast, BETA, DELTA, ABETA, Atable, sigma_B, omega) {
    .Call(`_SLCMRT_Update_DB`, J, M, K, alpha, nClass, Yast, BETA, DELTA, ABETA, Atable, sigma_B, omega)
}

#' @title Generate Random Delta Matrix
#' @description Generate a random Delta matrix with specified dimensions and parameters.
#'
#' This function generates a random Delta matrix with specified dimensions and parameters,
#' satisfying identifiability constraints.
#'
#' @param J Number of items.
#' @param K Number of attributes.
#' @param w Probability parameter specifying sparsity.
#' @return A random Delta matrix.
#' @export
#' @examples
#' J <- 10
#' K <- 3
#' w <- 0.5
random_D <- function(J, K, w) {
    .Call(`_SLCMRT_random_D`, J, K, w)
}

#' @title Generate Random Delta Matrix with Strict Identifiability
#' @description Generate a random Delta matrix with strict identifiability condition and specified dimensions and parameters.
#'
#' This function generates a random Delta matrix with strict identifiability condition.
#'
#' @param J Number of items.
#' @param K Number of attributes.
#' @param M Number of levels per attribute.
#' @param t Probability parameter specifying sparsity.
#' @param DtoQtable Table indicating the number of attributes per item.
#' @return A random Delta matrix satisfying the strict identifiability condition.
#' @export
random_D_strict <- function(J, K, M, t, DtoQtable) {
    .Call(`_SLCMRT_random_D_strict`, J, K, M, t, DtoQtable)
}

#' @title Permute Atable Indices
#' @description Permute indices of the attribute profile table based on specified parameters.
#'
#' This function permutes the indices of the attribute profile table (\code{Atable}) based on the provided parameters including
#' the number of classes (\code{nClass}), the number of attributes (\code{K}), the number of levels of attribute (\code{M}),
#' the vector of values (\code{vv}) and the permutation vector (\code{perm}).
#'
#' @param nClass Number of classes.
#' @param K Number of attributes.
#' @param M Levels of attribute.
#' @param vv Vector of values.
#' @param perm Permutation vector.
#' @return A vector representing the permuted indices of the attribute profile table.
#' @export
permuteAtableIndices <- function(nClass, K, M, vv, perm) {
    .Call(`_SLCMRT_permuteAtableIndices`, nClass, K, M, vv, perm)
}

#' @title Permute Attribute Order
#' @description Permute the order of attributes in the attribute profile table.
#'
#' This function permutes the order of attributes in the attribute profile table (\code{perm}) based on the provided parameters including
#' the number of classes (\code{nClass}), the number of attributes (\code{K}), the number of levels of attribute (\code{M}).
#'
#' @param nClass Number of classes.
#' @param K Number of attributes.
#' @param M Levels of attribute.
#' @param perm Matrix representing the attribute profile table, permat = permuteGeneral(c(0:(K-1))).
#' @return A matrix representing the permuted indices of the attribute profile table.
#' @export
permute_attr_order <- function(nClass, K, M, perm) {
    .Call(`_SLCMRT_permute_attr_order`, nClass, K, M, perm)
}

#' @title Generate Y Matrix
#' @description Generate a matrix of categorical responses based on probability cubes and class labels.
#'
#' This function generates a matrix of categorical responses (\code{Y}) based on the probability cubes (\code{PY_a}) and class labels (\code{CLASS}).
#'
#' @param PY_a A 3-dimensional cube containing probabilities for each class.
#' @param CLASS A numeric vector containing class labels for each respondent.
#' @param N Number of respondents.
#' @param J Number of response categories.
#' @param P Number of intervals for each response category.
#' @return A matrix representing the generated categorical responses.
#' @export
gen_Y <- function(PY_a, CLASS, N, J, P) {
    .Call(`_SLCMRT_gen_Y`, PY_a, CLASS, N, J, P)
}

#' @title Simulate Y Matrix
#' @description Simulate a matrix of categorical responses based on provided parameters.
#'
#' This function simulates a matrix of categorical responses (\code{Y}) based on the provided parameters including the number of respondents (\code{N}),
#' the number of items (\code{J}), the number of levels of attribute (\code{M}), the number of classes (\code{nClass}), class labels (\code{CLASS}),
#' attribute profile table (\code{Atable}), item response coefficient matrix (\code{BETA}), and item response threshold matrix (\code{Kappa}).
#'
#' @param N Number of respondents.
#' @param J Number of items.
#' @param M Levels of attribute.
#' @param nClass Number of classes.
#' @param CLASS A numeric vector containing class labels for each respondent.
#' @param Atable A matrix representing the attribute profile table.
#' @param BETA A matrix representing the item response coefficient matrix.
#' @param Kappa A matrix representing the item response threshold matrix.
#' @return A matrix of (\code{N}) by (\code{J}) representing the simulated categorical responses.
#' @export
simY <- function(N, J, M, nClass, CLASS, Atable, BETA, Kappa) {
    .Call(`_SLCMRT_simY`, N, J, M, nClass, CLASS, Atable, BETA, Kappa)
}

#' Compute the log-likelihood ratio test statistic for response time.
#'
#' This function computes the log-likelihood ratio test statistic.
#'
#' @param N Number of respondents.
#' @param J Number of items.
#' @param nClass Number of latent classes.
#' @param logt A matrix of log-transformed response time.
#' @param Eta A vector of item response time parameters.
#' @param Tau A vector of latent speed coefficients.
#' @param Atable A matrix of item attribute profiles.
#' @param H A matrix of item-attribute response time coefficients.
#' @param sigma2_t A vector of item response time variances.
#' @param pis Vector of latent class proportion parameters.
#' @return Log-likelihood ratio test statistic.
#' @export
RTLL <- function(N, J, nClass, logt, Eta, Tau, Atable, H, sigma2_t, pis) {
    .Call(`_SLCMRT_RTLL`, N, J, nClass, logt, Eta, Tau, Atable, H, sigma2_t, pis)
}

#' Compute the -2*log-likelihood for responses.
#'
#' This function computes the -2*log-likelihood for responses.
#'
#' @param N Number of respondents.
#' @param J Number of items.
#' @param P Number of response categories.
#' @param nClass Number of latent classes.
#' @param Y A matrix of observations with respondents by items.
#' @param pis Vector of latent class proportion parameters.
#' @param PY_a Cube of the joint probability distribution.
#' @return -2*log-likelihood.
#' @export
m2LL <- function(N, J, P, nClass, Y, pis, PY_a) {
    .Call(`_SLCMRT_m2LL`, N, J, P, nClass, Y, pis, PY_a)
}

